### PR TITLE
New plugin: Telegram

### PR DESCRIPTION
**Pull request by krueff**

### CODE REVIEW

**Comment by jacobmarshall** [comment]
Just as a note; the project status seems to be set to maintenance only.

[Bugsnag Notification Plugins - Project Status](https://github.com/bugsnag/bugsnag-notification-plugins#project-status-)

**Comment by duncanhewett** [comment]
@krueff - thanks very much for submitting this.  We are currently revamping all our team notification plugins to improve their consistency and reliability so we will include adding a Telegram plugin as part of this work.

**Comment by jacobmarshall** [comment]
Nice one @duncanhewett :+1:

**Comment by kattrali** [comment]
Closing in favor of the new notification plugins.

**Pull request closed without merging**
