### PR TITLE
Fix redmine priorityUrl to include apiKey

### PR DESCRIPTION
**Pull request by ConradIrwin**

### CODE REVIEW

**Comment by jacobmarshall** [comment]
Huh... this makes perfect sense, but... how has it worked before now? I've never needed to include the API key with that request.

**Comment by ArondeParon** [comment]
Reason for this pull request was an issue from me. This does not work for me without a key.

Additionally: it seems things are still broken. Has this PR been pushed into production yet?

**Comment by jessicard** [comment]
@ArondeParon Hey, I just pushed the new version out a moment ago - Take a look and let me know if things still seem broken!

**Comment by ArondeParon** [comment]
Thanks @jessicard! I just tested and don't want to disappoint, but it seems that Bugsnag is not even reaching our servers at this point. I get a HTTP 408 notice and don't see any log entries in my webserver log.

**Comment by snmaynard** [comment]
We had a small issue with the release. Can you try again?

**Pull request merged**
