### PR TITLE
[WIP] Add VictorOps plugin (forked from PagerDuty)

### PR DESCRIPTION
**Pull request by davejlong**
Adding a VictorOps plugin based on the PagerDuty plugin.

### CODE REVIEW

**Comment by davejlong** [comment]
There is something that looks like it might be a bug right now. When I run `coffee plugins/victorops/index.coffee --apiKey="..." --routingKey="dev"` I get the following output:

    $ ./node_modules/.bin/coffee plugins/victorops/index.coffee --apiKey="..." --routingKey="dev"
    Fired test event successfully
      undefined # <- Is this expected?

I'm just wondering if the `undefined` output is expected or not? I do successfully get the alert in VictorOps.

**Comment by snmaynard** [comment]
It is a small bug, we print out the error that comes from the plugin even if there wasnt one.

Thanks for this @davejlong - I'll try to get it pushed out asap.

**Comment by davejlong** [comment]
Any update on an expected release date for this plugin?

**Comment by davejlong** [comment]
I just saw that Bugsnag has deployed the VictorOps integration, but does not have a setting for the Routing Key which is required by VictorOps to route between different teams in VictorOps.

**Comment by snmaynard** [comment]
Ah the type value on that field was redundant. I've removed it and its showing up now.

Thanks for pointing it out!

**Pull request merged**
