### PR TITLE
bugsnag to datadog event stream

### PR DESCRIPTION
**Pull request by rtortora**
Mostly copied from the Slack one, with a small bit of tweaking, Datadog event streams are a bit limited in their formatting capabilities. But the event overlaying in Datadog is definitely working for me. Happy to make any changes necessary.

### CODE REVIEW

**Comment by snmaynard** [comment]
Thanks for this @rtortora - looks great! Only have one question, does datadog attribute special meaning to the environment tag or can we call it release stage (to keep it consistent with our terminology)?

Would it in any way be useful for a user to optionally specify tags for bugsnag events or can you already filter on the Bugsnag source?

**Comment by rtortora** [comment]
Datadog tags are totally generic, so it can definitely be release stage instead. I think it's common to call it environment (at least on a rails stack) in Datadog, but I can't think of any reason why a different name would be problematic. I think the main use case of this is creating a feed of Bugsnags that can show up in a Datadog dashboard or be overlayed on a graph, both of which would be filtering on any specific tag, so... This works for me! Would you like me to change it to release_stage instead of environment?

**Comment by snmaynard** [comment]
I think release stage makes sense as that is what it is called for all our languages. Let me know when you've made the change and I can merge and release

**Comment by rtortora** [comment]
Done! Looks like the standard multi-word approach for Datadog tags is "word-blah-blah" so I went with that. Figured I'd change it to app-version while I was at it. Let me know if you'd like any other changes.

**Comment by snmaynard** [comment]
Thanks @rtortora!

**Pull request merged**
