### PR TITLE
Support DoneDone

### PR DESCRIPTION
**Pull request by jjulian**
Finishes #160 

donedone requires POST data to be urlencoded, not json payload.

Events: `createIssue` and `comment` and `spike` have been tested successfully. I'm new to the BugSnag plugin-world, so I'd appreciate a look-over to make sure it's got all the cases covered.

### CODE REVIEW

**Comment by loopj** [comment]
Awesome! FYI superagent has built-in support for urlencoded form posts.

**Comment by jjulian** [comment]
Thanks for the heads-up @loopj! I removed the extra dependency.

**Comment by snmaynard** [comment]
Thanks @jjulian - gonna merge now and get it deployed soon!

**Comment by snmaynard** [comment]
Its live!

**Comment by jjulian** [comment]
It looks great! DoneDone is a little clunky with their config, you have to
choose a user *ID* to assign the issue upon creation. They do have an api
for browsing users. Is there a way to display a drop down in the bugsnag.com
configuration?

**Comment by snmaynard** [comment]
The best that we can do is typing something like their email address in and then in the plugin itself looking up the user id from that when the notification is triggered. This is something we could add in the future though (quite a few plugins have difficult to obtain details like this)

**Comment by spib** [comment]
Thanks for working on this, much appreciated. I've just given this a quick test and we're getting a 408 Request Timeout error when I click the 'Generate Test Issue' button. Any pointers on what that might be? I'm pretty sure I have all the config correct

**Comment by jjulian** [comment]
The DoneDone API does not mention error code 408, but I imagine there could
be runtime issues at any time. Try again? Maybe also try creating an issue?

**Pull request merged**
